
const usuarios = [
    {
        "id": 1,
        "nome": "Teste Tah 4",
        "email": "testetah4@email.com",
        "localizacao": "Bragan\u00e7a Paulista",
        "eh_doador": 1,
        "foto_perfil": "uploads\\Profile_Photo.jpg",
        "bio": "Teste Tah 4 - Senha",
        "senha": "$2b$12$kcgpFJzNa7Y0fVVmcqxRdeB/jipw3/skB8J.rna6JmaHArtDZaPq."
    },
    {
        "id": 2,
        "nome": "Talia Moura",
        "email": "tah@gmail.com",
        "localizacao": "Bragan\u00e7a Paulista",
        "eh_doador": 0,
        "foto_perfil": "uploads\\Profile_Photo.jpg",
        "bio": "Doadora de alimentos",
        "senha": "$2b$12$hfTPppYWD2a6CYdd0iWXm.Lg1629g9IiXdzaDHXlzEH1Xl2HU3K8y"
    },
    {
        "id": 3,
        "nome": "Nicoly Souza",
        "email": "nicoly@gmail.com",
        "localizacao": "Bragan\u00e7a Paulista",
        "eh_doador": 1,
        "foto_perfil": "uploads\\Backgroud.jpg",
        "bio": "Doadora de Alimentos",
        "senha": "$2b$12$G76NDe/dIsJggT0NypMenuj2.1I6y8ULux2EhYOCAzEbp7RWLlnBq"
    },
    {
        "id": 4,
        "nome": "Rafael Macedo ",
        "email": "rafa@gmail.com",
        "localizacao": "S\u00e3o Paulo",
        "eh_doador": 1,
        "foto_perfil": "uploads\\Backgroud.jpg",
        "bio": "Sou um doador de alimentos",
        "senha": "$2b$12$mSpE8h6Agvge4dJnnmQurecn5mp8oUG5i7.yrGkMUHgxA23EyHaAG"
    },
    {
        "id": 5,
        "nome": "Talia Moura",
        "email": "talia@email.com",
        "localizacao": "Bragan\u00e7a Paulista",
        "eh_doador": 0,
        "foto_perfil": "uploads\\Profile_Photo.jpg",
        "bio": "Trabalho com uma ONG de arrecada\u00e7\u00e3o de Alimentos",
        "senha": "$2b$12$Dteolnxo/LMcd2//ykDfhefXrn1SNcSjaN3.FK9tLyVj8sJOt2SSa"
    },
    {
        "id": 6,
        "nome": "Thiago Macedo",
        "email": "thi@email.com",
        "localizacao": "Bragan\u00e7a Paulista",
        "eh_doador": 0,
        "foto_perfil": "uploads\\Backgroud.jpg",
        "bio": "Sou um Doador de Alimentos",
        "senha": "$2b$12$lDLJx/Oaaf6qpf07gmvzSOLAZgqqURCuN1WU.xgAkkc1Y4C6Utxjm"
    },
    {
        "id": 7,
        "nome": "Thiago Cavalcante",
        "email": "thia@email.com",
        "localizacao": "Bragan\u00e7a Paulista",
        "eh_doador": 0,
        "foto_perfil": "uploads\\Backgroud.jpg",
        "bio": "Sou um Doador de Alimentos",
        "senha": "$2b$12$l.EV4KZIhE80UoJuMrZVjuYip213z7HWRcNLxVJAIC3XeL928sMnq"
    },
    {
        "id": 8,
        "nome": "Thiago Cavalcante",
        "email": "thiago@gmail.com",
        "localizacao": "Bragan\u00e7a Paulista",
        "eh_doador": 1,
        "foto_perfil": "uploads\\Backgroud.jpg",
        "bio": "qasgfedrsg",
        "senha": "$2b$12$t7BgOdCzDKQ/NV77HDh/eecqZPq3NAtKWfDs2uImyVqjUH.Qp7rHC"
    },
    {
        "id": 9,
        "nome": "Talia Moura",
        "email": "taliam@gmail.com",
        "localizacao": "Bragan\u00e7a Paulista",
        "eh_doador": 1,
        "foto_perfil": "uploads\\Profile_Photo.jpg",
        "bio": "Sou doadora de Alimentos ",
        "senha": "$2b$12$jlXgtwgM51xOIHxyHV8x8OlIGXuLM7hVx9T0BJGjd./wJzKDpMENW"
    }
];
const postagens = [
    {
        "id": 1,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "Arroz Branco",
        "localizacao": "Rua Teste, 123",
        "data_validade": "2025-02-24",
        "quantidade": "5",
        "contato": "123456789",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": 0
    },
    {
        "id": 2,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "Arroz Branco Tipo 1",
        "localizacao": "Rua Teste, 123",
        "data_validade": "2024-12-27",
        "quantidade": "5",
        "contato": "123456789",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": "false"
    },
    {
        "id": 3,
        "usuario_id": 1,
        "titulo": "fewytweh",
        "descricao": "dfghedsfhg",
        "localizacao": "gdrfshw",
        "data_validade": "2025-01-01",
        "quantidade": "3",
        "contato": "123456789",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": "false"
    },
    {
        "id": 4,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "Arroz branco",
        "localizacao": "sp",
        "data_validade": "2024-12-20",
        "quantidade": "5",
        "contato": "123456789",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": "false"
    },
    {
        "id": 5,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "Arroz B TP 1",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2024-12-27",
        "quantidade": "5",
        "contato": "11 112244557",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": "false"
    },
    {
        "id": 6,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "Arroz B TP 1",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2024-12-28",
        "quantidade": "5",
        "contato": "11 112244557",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": "false"
    },
    {
        "id": 7,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "Arroz B TP 1",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2024-12-27",
        "quantidade": "5",
        "contato": "11 112244557",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": "false"
    },
    {
        "id": 8,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "A B TP 1",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2024-12-28",
        "quantidade": "6",
        "contato": "11 112244557",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": null
    },
    {
        "id": 9,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "A B TP 1",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2024-12-28",
        "quantidade": "56",
        "contato": "11 112244557",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 10,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "A B TP 1",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2024-12-27",
        "quantidade": "50",
        "contato": "11 112244557",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": 0
    },
    {
        "id": 11,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "A B TP 1",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2024-12-28",
        "quantidade": "50",
        "contato": "11 112244557",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 12,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "fdghynbdx",
        "localizacao": "sgdf",
        "data_validade": "2024-12-20",
        "quantidade": "50",
        "contato": "11 112244557",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 13,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "egsdf",
        "localizacao": "sgdf",
        "data_validade": "2024-12-21",
        "quantidade": "50",
        "contato": "11 112244557",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 14,
        "usuario_id": 1,
        "titulo": "Postagem Teste Front",
        "descricao": "gasrd",
        "localizacao": "sgdf",
        "data_validade": "2024-12-21",
        "quantidade": "50",
        "contato": "11 112244557",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 15,
        "usuario_id": 1,
        "titulo": "Teste",
        "descricao": "agewrsd",
        "localizacao": "grsad",
        "data_validade": "2024-12-20",
        "quantidade": "50",
        "contato": "11 112244557",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 16,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "dfshges",
        "localizacao": "sgdf",
        "data_validade": "2024-12-21",
        "quantidade": "50",
        "contato": "11 112244557",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 17,
        "usuario_id": 1,
        "titulo": "Arroz",
        "descricao": "refgt",
        "localizacao": "sgdf",
        "data_validade": "2024-12-21",
        "quantidade": "61",
        "contato": "11 112244557",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 18,
        "usuario_id": 4,
        "titulo": "Arroz",
        "descricao": "Arroz Branco Tipo 1",
        "localizacao": "S\u00e3o Paulo, SP",
        "data_validade": "2025-01-24",
        "quantidade": "3",
        "contato": "11912345678",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_135849.png",
        "disponivel": 1
    },
    {
        "id": 19,
        "usuario_id": 4,
        "titulo": "Feij\u00e3o",
        "descricao": "Feij\u00e3o Preto",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2025-02-06",
        "quantidade": "5",
        "contato": "11985632478",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_143500.png",
        "disponivel": 0
    },
    {
        "id": 20,
        "usuario_id": 4,
        "titulo": "Macarr\u00e3o",
        "descricao": "Macarr\u00e3o tipo Parafuso",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2025-03-13",
        "quantidade": "30",
        "contato": "11985632478",
        "imagem": "uploads\\Captura_de_tela_2024-12-11_180324.png",
        "disponivel": 0
    },
    {
        "id": 21,
        "usuario_id": 5,
        "titulo": "Macarr\u00e3o",
        "descricao": "dfxhrfd",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2024-12-25",
        "quantidade": "30",
        "contato": "11985632478",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 22,
        "usuario_id": 5,
        "titulo": "Macarr\u00e3o Parafuso",
        "descricao": "Macarr\u00e3o Tipo Parafuso",
        "localizacao": "Extrema, MG",
        "data_validade": "2026-01-05",
        "quantidade": "10",
        "contato": "11912345678",
        "imagem": "uploads\\Captura_de_tela_2024-12-10_145256.png",
        "disponivel": 1
    },
    {
        "id": 23,
        "usuario_id": 5,
        "titulo": "wesgdt",
        "descricao": "gfdsh",
        "localizacao": "sdfh",
        "data_validade": "2024-12-19",
        "quantidade": "5",
        "contato": "119123456789",
        "imagem": null,
        "disponivel": 0
    },
    {
        "id": 24,
        "usuario_id": 9,
        "titulo": "Macarr\u00e3o Espaguete",
        "descricao": "Macarr\u00e3o Espaguete",
        "localizacao": "Bragan\u00e7a Paulista",
        "data_validade": "2025-02-06",
        "quantidade": "10",
        "contato": "11912345678",
        "imagem": "uploads\\Captura_de_tela_2024-12-11_180324.png",
        "disponivel": 1
    }
];

export { usuarios, postagens };
